name: Auto Build DshanNezhaSTU Release Linux system.
on: workflow_dispatch
jobs:
  build-all-os:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: debian-linux

      - name: Install depends
        run: sudo apt install  autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev swig libssl-dev python3-distutils python3-dev debootstrap debian-ports-archive-keyring  qemu-user-static qemu-system qemu-utils qemu-system-misc binfmt-support  parted  kpartx
        
      - name: Pull & update submodules recursively
        working-directory: ./debian-linux
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote   
    
      - name: build boot0_spl opensbi uboot kernel
        working-directory: ./debian-linux
        run: ls -l && bash build.sh

      - name: Create debian rootfs
        working-directory: ./debian-linux
        run: bash setup_rootfs.sh

      - name: Create debian sdcard.img
        working-directory: ./debian-linux
        run: bash output_images.sh
        
      - name: gzip sdcard.img
        working-directory: ./debian-linux        
        run: bash gzip NezhaSTU-Sdcard.img
      
      - run: bash ls  ${{runner.workspace}} && echo ${{runner.workspace}}

      - name: Upload debian sdcrad images
        uses: actions/upload-artifact@v2
        with:
          name: "Download artifacts - debian images."
          path: ${{runner.workspace}}/debian-linux/debian-linux/NezhaSTU-Sdcard.img.gz
